export { default as Hero } from './home/Hero'
export { default as Achievements } from './home/Achievements'
export { default as Gallery } from './home/Gallery'
export { default as Reality } from './home/Reality'
export { default as Audience } from './home/Audience'
export { default as Story } from './about/Story'
